import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  InspectionRoom,
  InspectionItem,
  InspectionPhoto,
  InspectionReport,
  CONDITION_LABELS,
  CLEANLINESS_LABELS,
  INSPECTION_TYPE_LABELS,
  PROPERTY_TYPE_LABELS,
  FURNISHED_STATUS_LABELS,
  ConditionRating,
  CleanlinessRating,
  InspectionType,
  PropertyType,
  FurnishedStatus,
} from "@/types/database";
import { format } from "date-fns";

// Brand colours (LISTD navy/teal)
const NAVY: [number, number, number] = [15, 23, 42];
const TEAL: [number, number, number] = [20, 184, 166];
const WHITE: [number, number, number] = [255, 255, 255];
const LIGHT_GRAY: [number, number, number] = [241, 245, 249];
const DARK_GRAY: [number, number, number] = [100, 116, 139];

interface JobProperty {
  address_line_1: string;
  address_line_2: string | null;
  city: string;
  postcode: string;
  property_type: string;
  bedrooms: number;
  bathrooms: number;
  kitchens: number;
  living_rooms: number;
  furnished_status: string;
  heavily_furnished: boolean;
}

interface ReportJob {
  id: string;
  inspection_type: string;
  scheduled_date: string;
  special_instructions: string | null;
  properties: JobProperty;
}

interface GenerateReportParams {
  job: ReportJob;
  report: InspectionReport;
  rooms: InspectionRoom[];
  items: InspectionItem[];
  photos: InspectionPhoto[];
  meterReadings: any[];
  keysInfo: any[];
  alarmsData: any[];
}

function conditionLabel(c: string | null): string {
  if (!c) return "—";
  return CONDITION_LABELS[c as ConditionRating] || c;
}

function cleanlinessLabel(c: string | null): string {
  if (!c) return "—";
  return CLEANLINESS_LABELS[c as CleanlinessRating] || c;
}

async function loadImage(url: string): Promise<string | null> {
  try {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export async function generateInspectionPDF(
  params: GenerateReportParams,
  onProgress?: (pct: number) => void
): Promise<jsPDF> {
  const { job, report, rooms, items, photos, meterReadings, keysInfo, alarmsData } = params;
  const property = job.properties;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - 20) {
      doc.addPage();
      y = margin;
      addFooter();
    }
  };

  const addFooter = () => {
    const pageCount = doc.getNumberOfPages();
    doc.setFontSize(7);
    doc.setTextColor(...DARK_GRAY);
    doc.text(
      `Page ${pageCount} — Generated by LISTD  •  ${format(new Date(), "dd/MM/yyyy HH:mm")}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );
  };

  // ── Cover / Header ──────────────────────────────────────────────
  // Navy header band
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageWidth, 52, "F");

  // Teal accent bar
  doc.setFillColor(...TEAL);
  doc.rect(0, 52, pageWidth, 3, "F");

  // Brand name
  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor(...WHITE);
  doc.text("LISTD", margin, 22);

  // Report type
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(
    INSPECTION_TYPE_LABELS[job.inspection_type as InspectionType] || job.inspection_type,
    margin,
    34
  );

  // Date
  doc.setFontSize(10);
  doc.text(format(new Date(job.scheduled_date), "dd MMMM yyyy"), margin, 44);

  // Address on right
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  const addr = property.address_line_1;
  doc.text(addr, pageWidth - margin, 22, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const addr2 = [property.address_line_2, property.city, property.postcode]
    .filter(Boolean)
    .join(", ");
  doc.text(addr2, pageWidth - margin, 30, { align: "right" });

  y = 62;

  // ── Property Details ────────────────────────────────────────────
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...NAVY);
  doc.text("Property Details", margin, y);
  y += 7;

  const propDetails = [
    ["Type", PROPERTY_TYPE_LABELS[property.property_type as PropertyType] || property.property_type],
    ["Furnished", FURNISHED_STATUS_LABELS[property.furnished_status as FurnishedStatus] || property.furnished_status],
    ["Bedrooms", String(property.bedrooms)],
    ["Bathrooms", String(property.bathrooms)],
    ["Kitchens", String(property.kitchens)],
    ["Living Rooms", String(property.living_rooms)],
  ];

  autoTable(doc, {
    startY: y,
    head: [],
    body: propDetails,
    theme: "plain",
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 2, textColor: NAVY },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 40, textColor: DARK_GRAY as any },
      1: { cellWidth: contentWidth - 40 },
    },
  });

  y = (doc as any).lastAutoTable.finalY + 10;
  onProgress?.(10);

  // ── Schedule of Condition ───────────────────────────────────────
  ensureSpace(30);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...NAVY);
  doc.text("Schedule of Condition", margin, y);
  y += 7;

  const scheduleRows = rooms.map((room) => {
    const roomItems = items.filter((i) => i.room_id === room.id);
    const completed = roomItems.filter((i) => i.completed).length;
    const total = roomItems.length;

    // Derive overall
    const conditions = roomItems.map((i) => i.condition).filter(Boolean);
    let overall = room.overall_condition
      ? conditionLabel(room.overall_condition)
      : conditions.length > 0
      ? conditionLabel(conditions[0])
      : "—";

    return [room.room_name, String(total), `${completed}/${total}`, overall];
  });

  autoTable(doc, {
    startY: y,
    head: [["Room / Area", "Items", "Completed", "Overall Condition"]],
    body: scheduleRows,
    margin: { left: margin, right: margin },
    headStyles: {
      fillColor: NAVY as any,
      textColor: WHITE as any,
      fontStyle: "bold",
      fontSize: 8,
    },
    styles: { fontSize: 8, cellPadding: 3 },
    alternateRowStyles: { fillColor: LIGHT_GRAY as any },
  });

  y = (doc as any).lastAutoTable.finalY + 10;
  onProgress?.(20);

  // ── Room Details ────────────────────────────────────────────────
  for (let ri = 0; ri < rooms.length; ri++) {
    const room = rooms[ri];
    const roomItems = items.filter((i) => i.room_id === room.id);
    const roomPhotos = photos.filter((p) => p.room_id === room.id);

    ensureSpace(40);

    // Room heading with teal accent
    doc.setFillColor(...TEAL);
    doc.rect(margin, y - 1, 3, 8, "F");
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text(room.room_name, margin + 6, y + 5);
    y += 12;

    // Items table
    if (roomItems.length > 0) {
      const itemRows = roomItems.map((item) => [
        item.item_name,
        item.description || "—",
        conditionLabel(item.condition),
        cleanlinessLabel(item.cleanliness),
        item.condition_notes || item.cleanliness_notes || "—",
      ]);

      autoTable(doc, {
        startY: y,
        head: [["Item", "Description", "Condition", "Cleanliness", "Notes"]],
        body: itemRows,
        margin: { left: margin, right: margin },
        headStyles: {
          fillColor: NAVY as any,
          textColor: WHITE as any,
          fontStyle: "bold",
          fontSize: 7,
        },
        styles: { fontSize: 7, cellPadding: 2, overflow: "linebreak" },
        columnStyles: {
          0: { cellWidth: 28 },
          1: { cellWidth: 35 },
          2: { cellWidth: 28 },
          3: { cellWidth: 28 },
          4: { cellWidth: contentWidth - 119 },
        },
        alternateRowStyles: { fillColor: LIGHT_GRAY as any },
      });

      y = (doc as any).lastAutoTable.finalY + 5;
    }

    // Room notes
    if (room.notes) {
      ensureSpace(15);
      doc.setFontSize(7);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(...DARK_GRAY);
      doc.text(`Notes: ${room.notes}`, margin + 6, y);
      y += 6;
    }

    // Room photos (grid of thumbnails)
    if (roomPhotos.length > 0) {
      ensureSpace(40);
      const thumbSize = 30;
      const gap = 4;
      const perRow = Math.floor(contentWidth / (thumbSize + gap));
      let col = 0;

      for (const photo of roomPhotos) {
        if (col >= perRow) {
          col = 0;
          y += thumbSize + gap + (4);
          ensureSpace(thumbSize + gap);
        }

        const imgData = await loadImage(photo.photo_url);
        if (imgData) {
          const x = margin + col * (thumbSize + gap);
          doc.addImage(imgData, "JPEG", x, y, thumbSize, thumbSize);

          if (photo.caption) {
            doc.setFontSize(5);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(...DARK_GRAY);
            doc.text(
              photo.caption.slice(0, 30),
              x + thumbSize / 2,
              y + thumbSize + 3,
              { align: "center" }
            );
          }
          col++;
        }
      }
      y += thumbSize + 8;
    }

    y += 5;
    onProgress?.(20 + Math.round((ri / rooms.length) * 50));
  }

  // ── Meter Readings ──────────────────────────────────────────────
  if (meterReadings.length > 0) {
    ensureSpace(30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text("Meter Readings", margin, y);
    y += 7;

    const meterRows = meterReadings.map((m: any) => [
      m.type || "—",
      m.serialNumber || "—",
      m.location || "—",
      m.reading || "—",
      m.unit || "—",
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Type", "Serial No.", "Location", "Reading", "Unit"]],
      body: meterRows,
      margin: { left: margin, right: margin },
      headStyles: { fillColor: NAVY as any, textColor: WHITE as any, fontStyle: "bold", fontSize: 8 },
      styles: { fontSize: 8, cellPadding: 3 },
      alternateRowStyles: { fillColor: LIGHT_GRAY as any },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }
  onProgress?.(75);

  // ── Keys ────────────────────────────────────────────────────────
  if (keysInfo.length > 0) {
    ensureSpace(30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text("Keys", margin, y);
    y += 7;

    const keyRows = keysInfo.map((k: any) => [
      k.type || "—",
      String(k.quantity || 1),
      k.description || "—",
      k.status || "—",
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Key Type", "Qty", "Description", "Status"]],
      body: keyRows,
      margin: { left: margin, right: margin },
      headStyles: { fillColor: NAVY as any, textColor: WHITE as any, fontStyle: "bold", fontSize: 8 },
      styles: { fontSize: 8, cellPadding: 3 },
      alternateRowStyles: { fillColor: LIGHT_GRAY as any },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ── Alarms & Safety ────────────────────────────────────────────
  if (alarmsData.length > 0) {
    ensureSpace(30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text("Safety Devices", margin, y);
    y += 7;

    const alarmRows = alarmsData.map((a: any) => [
      a.type || "—",
      a.location || "—",
      a.testResult || "—",
      a.expiryDate || "—",
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Device Type", "Location", "Test Result", "Expiry"]],
      body: alarmRows,
      margin: { left: margin, right: margin },
      headStyles: { fillColor: NAVY as any, textColor: WHITE as any, fontStyle: "bold", fontSize: 8 },
      styles: { fontSize: 8, cellPadding: 3 },
      alternateRowStyles: { fillColor: LIGHT_GRAY as any },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }
  onProgress?.(85);

  // ── General Notes ──────────────────────────────────────────────
  if (report.general_notes) {
    ensureSpace(25);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...NAVY);
    doc.text("General Notes", margin, y);
    y += 7;

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    const lines = doc.splitTextToSize(report.general_notes, contentWidth);
    doc.text(lines, margin, y);
    y += lines.length * 4.5 + 10;
  }

  // ── Glossary of Terms ──────────────────────────────────────────
  ensureSpace(80);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...NAVY);
  doc.text("Glossary of Terms Used Within Report", margin, y);
  y += 7;

  const glossaryRows = [
    ["New Condition", "Unused condition."],
    ["Excellent / Very Good", "No marks, tears, stains, generally under one-year old."],
    ["Good", "Signs of slight wear, generally lightly worn."],
    ["Fair", "Signs of age, frayed, small light stains, marks and discolouration."],
    ["Poor", "Extensive signs of wear and tear, extensive stains/marks/tears/chips, still functional."],
    ["Very Poor", "Extensively damaged/faulty items, large stains, upholstery torn and/or dirty, pet odour/hairs."],
    ["Weathered", "Outside, signs of slight wear, generally lightly worn."],
    ["Fair Weathered", "Outside, signs of age, frayed, small light stains and marks, discolouration."],
    ["Poor Weathered", "Outside, extensive signs of wear and tear. Still functional."],
    ["Used Condition", "Opened and used as expected."],
    ["Professional Standard", "All surfaces clean, dust free, polished, free from residue and limescale."],
    ["Domestic Standard", "All surfaces clean; minor dust or grubby marks in places."],
    ["Further Cleaning Required", "Dusty or grubby surfaces. Light cleaning would be necessary."],
    ["Poor Standard", "Requires a thorough full clean throughout."],
    ["Dusty", "Light dust which could easily be removed with a cloth or vacuum."],
    ["Debris or Residue", "Particles which could be removed with cleaning."],
    ["Lightly Soiled", "Light or sticky marks that require light cleaning products to remove."],
    ["Soiled / Grubby", "Heavy or sticky marks that require cleaning products to remove."],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Term", "Definition"]],
    body: glossaryRows,
    margin: { left: margin, right: margin },
    headStyles: { fillColor: NAVY as any, textColor: WHITE as any, fontStyle: "bold", fontSize: 8 },
    styles: { fontSize: 7, cellPadding: 2.5, overflow: "linebreak" },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 38 },
      1: { cellWidth: contentWidth - 38 },
    },
    alternateRowStyles: { fillColor: LIGHT_GRAY as any },
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // ── Disclaimer ─────────────────────────────────────────────────
  ensureSpace(30);
  doc.setFontSize(7);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(...DARK_GRAY);
  const disclaimer =
    "This report has been prepared by a LISTD inventory clerk and provides a fair and accurate representation of the property at the time of inspection. " +
    "All observations are made in good faith. This document may be used as evidence in any deposit dispute resolution.";
  const discLines = doc.splitTextToSize(disclaimer, contentWidth);
  doc.text(discLines, margin, y);

  // Add footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(...DARK_GRAY);
    doc.text(
      `Page ${i} of ${totalPages}  •  LISTD Inspection Report  •  ${format(new Date(), "dd/MM/yyyy HH:mm")}`,
      pageWidth / 2,
      pageHeight - 8,
      { align: "center" }
    );
    // Bottom teal accent
    doc.setFillColor(...TEAL);
    doc.rect(0, pageHeight - 3, pageWidth, 3, "F");
  }

  onProgress?.(100);
  return doc;
}

export function downloadReport(doc: jsPDF, filename: string) {
  doc.save(filename);
}
